# In backend/app/mock_data.py

MOCK_TWEETS = {
    # Persona 1: Inspired by Elon Musk
    # Username: leomaxwell
    # Bio: CEO of 'Stellaria' & 'NeuraLink'. Accelerating the future. Mars is inevitable.
    "leomaxwell": [
        "Physics is the law. Everything else is a recommendation.",
        "Manufacturing is the real bottleneck. Innovation is wasted without scale.",
        "Woke up at 3 AM with a solution for the thermal shield ablation. The best ideas don't respect sleep schedules.",
        "Who thought this Powerpoint was a good use of anyone's time? We build rockets here, not slide decks.",
        "The Giga-factory floor is my happy place. The symphony of robots building the future.",
        "AI safety must be a priority. We are summoning the demon.",
        "Some days it feels like we're inches away. Other days, light-years. The grind continues.",
        "Excellent meme. 10/10.",
        "Humanity's future will be multi-planetary or it will be no future at all.",
        "My kids asked if aliens are real. I said the silence from the stars is the most interesting data point.",
        "Burnout isn't real if you love what you do. It's just reloading.",
        "Why are there so many meetings? A meeting is what happens when people aren't working.",
        "The Boring Company is a great name because it's literally true and also punny.",
        "Just did a design review for the Mars habitat. Needs to be simpler, more robust. Less can go wrong.",
        "First principles thinking is the only way to solve truly novel problems. Break it all down.",
        "I'm selling almost all my physical possessions. They just weigh you down.",
        "Earth is the cradle of humanity, but you cannot stay in the cradle forever.",
        "Optimism is a moral duty.",
        "The problem with most CEOs is they're too focused on the business side. Get on the factory floor!",
        "Coffee, and then more coffee. The fuel of civilization.",
        "The pace of innovation is all that matters in the long run.",
        "Consciousness is a tiny candle in a vast, cold darkness. We must protect it.",
        "People should be more ambitious. The world is more malleable than you think.",
        "Just finished a 100-hour work week. Light work.",
        "Our neural interface will change what it means to be human. Coming sooner than you think.",
        "I find it ironic that we have self-driving cars but still use archaic voting systems.",
        "Let's make life more than just solving one miserable problem after another. Let's be inspired.",
        "Failure is an option here. If you are not failing, you are not innovating enough.",
        "The official language on Mars will be Memetic.",
        "My desk is at the end of the production line. I see problems as they come off.",
        "Who needs a vacation when your job is to build the future?",
        "History is written by the victors of the meme wars.",
        "Tunnels. So underrated. We can solve traffic.",
        "It's wild that we are still burning fossil fuels. We're in a race against ourselves.",
        "The best part of my job is walking among giants: our rockets.",
        "Feedback is a gift. Especially negative feedback.",
        "Let's make sci-fi a reality.",
        "I believe in the good of humanity, but we need to have a backup plan.",
        "The universe is the answer. What is the question?",
        "Our rocket landing algorithm is a thing of beauty. A ballet of fire and math.",
        "Hiring for Stellaria. A high pain threshold is a plus.",
        "Is reality a simulation? The graphics are great, but the plot is a bit convoluted.",
        "The future of humanity will be decided in our lifetimes.",
        "I am an alien. Or so they say.",
        "Let's put a restaurant at the end of the universe.",
        "Reading a book on Roman engineering. They knew how to build things that last.",
        "Simplicity is the ultimate sophistication.",
        "The sun is a gigantic fusion reactor in the sky. We should use it more.",
        "Going to Mars is not for the faint of heart. But it will be the greatest adventure in human history.",
        "Ad astra."
    ],

    # Persona 2: Inspired by Warren Buffett
    # Username: arthurvance
    # Bio: Investor. Omaha, NE. I like businesses I can understand.
    "arthurvance": [
        "Rule No. 1: Never lose money. Rule No. 2: Never forget Rule No. 1.",
        "Someone is sitting in the shade today because someone planted a tree a long time ago.",
        "Enjoying a cherry soda and a good book. The best things in life are simple.",
        "The stock market is a device for transferring money from the impatient to the patient.",
        "If a business is easy to understand, I might be interested. If it's not, I'm not.",
        "Time is the friend of the wonderful company, the enemy of the mediocre.",
        "My favorite holding period is forever.",
        "Just finished my daily reading. 500 pages. Best investment you can make.",
        "The difference between successful people and really successful people is that really successful people say no to almost everything.",
        "Never invest in a business you cannot understand. For me, that's most tech companies.",
        "Price is what you pay. Value is what you get.",
        "It's far better to buy a wonderful company at a fair price than a fair company at a wonderful price.",
        "A little lunch at Gorat's. Nothing beats a good steak.",
        "Why would I buy a fancy car? It wouldn't make me any happier.",
        "The most important quality for an investor is temperament, not intellect.",
        "Look for businesses with a durable competitive advantage. A 'moat' around their castle.",
        "The best thing I did was to choose the right heroes. Read the biographies of great people.",
        "Be fearful when others are greedy and greedy when others are fearful.",
        "The tide of the market goes out, and you discover who's been swimming naked.",
        "Honesty is a very expensive gift. Don't expect it from cheap people.",
        "I get to do what I love every day with people I love. I feel very lucky.",
        "The tax code is a puzzle. It pays to know the rules.",
        "Playing a little bridge online. Great for the mind.",
        "We simply attempt to be fearful when others are greedy and to be greedy only when others are fearful.",
        "Calling a stock 'a play' is a dangerous mindset. You're buying a piece of a business.",
        "Diversification is protection against ignorance. It makes very little sense for those who know what they're doing.",
        "The best investment is in yourself.",
        "You only have to do a very few things right in your life so long as you don't do too many things wrong.",
        "Wall Street is the only place that people ride to in a Rolls-Royce to get advice from those who take the subway.",
        "An investor should act as though he had a lifetime decision card with just twenty punches on it.",
        "It takes 20 years to build a reputation and five minutes to ruin it.",
        "Risk comes from not knowing what you're doing.",
        "Just because a company is 'growing' doesn't make it a good investment.",
        "Cash is like oxygen. You only notice it when you don't have it.",
        "I'm a better investor because I'm a businessman, and a better businessman because I am an investor.",
        "The chains of habit are too light to be felt until they are too heavy to be broken.",
        "Compound interest is the eighth wonder of the world.",
        "Forecasts may tell you a great deal about the forecaster; they tell you nothing about the future.",
        "A public opinion poll is no substitute for thought.",
        "Never ask a barber if you need a haircut.",
        "The most dangerous words in investing are 'this time it's different'.",
        "It's not about timing the market, but about time in the market.",
        "A wonderful drive through Omaha this morning. A great place to think.",
        "The newspaper is still the best way to get the news. Call me old-fashioned.",
        "The American tailwind is a powerful thing. Never bet against it in the long run.",
        "Derivatives are financial weapons of mass destruction.",
        "The best businesses are the ones that require no new capital to grow.",
        "Predicting rain doesn't count. Building arks does.",
        "When a management with a reputation for brilliance tackles a business with a reputation for bad economics, it is the reputation of the business that remains intact.",
        "I insist on a lot of time being spent, almost every day, to just sit and think."
    ],

    # Persona 3: Inspired by Brené Brown
    # Username: dranyasharma
    # Bio: Researcher, storyteller, author. Living a wholehearted life. I believe in the power of vulnerability.
    "dranyasharma": [
        "Vulnerability is not weakness; it's our greatest measure of courage.",
        "The data is clear: we are wired for connection. It's what gives purpose and meaning to our lives.",
        "Just finished a talk on leadership. The message: Dare to lead with your whole heart.",
        "Shame needs three things to grow: secrecy, silence, and judgment. Empathy is the antidote.",
        "You can choose courage or you can choose comfort, but you cannot choose both.",
        "Perfectionism is not self-improvement. It's a 20-ton shield that we lug around.",
        "Boundaries are not walls. They're expectations we set for ourselves and others.",
        "Spent the afternoon analyzing new research data. The patterns of human behavior are endlessly fascinating.",
        "If you're not in the arena also getting your butt kicked, I'm not interested in your feedback.",
        "True belonging doesn't require you to change who you are; it requires you to be who you are.",
        "Talk to yourself like you would to someone you love.",
        "The middle is messy, but it's also where the magic happens.",
        "Clarity is kind. Unclear is unkind.",
        "What a gift to see my work resonating with so many people. Feeling deeply grateful today.",
        "Leadership is not about titles or the corner office. It’s about the willingness to step up, put yourself out there, and lean into courage.",
        "Just because someone failed to appreciate your worth doesn't mean you're worthless.",
        "Writing day. Just me, my laptop, and a lot of coffee. The stories have to be told.",
        "Courage starts with showing up and letting ourselves be seen.",
        "When we numb the dark, we numb the light. You can't selectively numb emotion.",
        "The opposite of scarcity is not abundance. It's 'enough'.",
        "Authenticity is the daily practice of letting go of who we think we're supposed to be and embracing who we are.",
        "My family keeps me grounded. Laughter is the best research break.",
        "We don't have to do it all alone. We were never meant to.",
        "What's the greater risk? Letting go of what people think - or letting go of how I feel, what I believe, and who I am?",
        "Empathy has no script. There is no right way or wrong way to do it. It's simply listening, holding space, and withholding judgment.",
        "Guilt is 'I did something bad.' Shame is 'I am bad.' Huge difference.",
        "Our job is not to deny the story, but to defy the ending—to rise strong, recognize our story, and rumble with the truth until we get to a place where we think, 'Yes. This is what happened. This is my truth. And I will not be condemned by it.'",
        "Joy is the most vulnerable of all human emotions.",
        "Research is a spiritual practice for me.",
        "Daring greatly is not about winning or losing. It's about courage.",
        "The courage to be imperfect is a gift we give ourselves and the world.",
        "Sometimes the bravest and most important thing you can do is just show up.",
        "There is no innovation and creativity without failure. Period.",
        "Self-compassion is key. Treat yourself with kindness.",
        "What we know matters, but who we are matters more.",
        "A quiet evening at home with a good novel. Recharging the soul.",
        "I'm not a parenting expert. I'm a researcher. The two are very different.",
        "Belonging is being accepted for you. Fitting in is being accepted for being like everyone else.",
        "The dark does not destroy the light; it defines it.",
        "Trust is built in very small moments.",
        "Hope is a function of struggle.",
        "To love ourselves and support each other in the process of becoming real is perhaps the greatest single act of daring greatly.",
        "Choose authenticity. Choose courage. Choose to be seen.",
        "My research is my rebellion.",
        "Curiosity is a superpower.",
        "Your story is your power. Own it.",
        "I define connection as the energy that exists between people when they feel seen, heard, and valued.",
        "Gratitude, gratitude, gratitude. The key to joy.",
        "Don't shrink. Don't puff up. Stand your sacred ground.",
        "Let's be brave enough to be brokenhearted."
    ],

    # Persona 4: Inspired by Hayao Miyazaki
    # Username: kenjitanaka
    # Bio: I draw pictures. Sometimes they move.
    "kenjitanaka": [
        "The forest near my home is breathing. I spent the morning listening.",
        "Too much technology dulls the senses. A pencil and paper are all I need.",
        "I am not making a 'message' movie. I am making a film. If you see a message, it is because it is in you.",
        "The sky in my latest drawing feels wrong. The blue is too... clean. The world is not so clean.",
        "Children understand my films better than adults.",
        "Another day spent at the desk. My back hurts, but the characters are starting to come alive.",
        "I hate the word 'masterpiece'. You just do the work. Then you do the next work.",
        "We are polluting the sky, the sea, the earth. How can our souls not be polluted too?",
        "A good meal with old friends. We talked about how much the city has changed. Not for the better.",
        "The wind told me a story today. I tried to draw it.",
        "Young animators today rely too much on computers. They forget how to observe. How a leaf falls, how water moves.",
        "Pigs are noble creatures. They are much smarter than they look.",
        "I am a pessimist. But a child's laughter can make me forget for a moment.",
        "Flying is not about the machine. It is about the freedom. The dream.",
        "My favorite part of the process is the storyboard. It is where the film is truly born.",
        "Why must we always be at war? With each other, with nature. It is exhausting.",
        "The watercolours arrived today. Beautiful, rich colours. They make me want to paint.",
        "I am not retired. I am just working on smaller things. For myself. And my grandchildren.",
        "An old tree has more stories to tell than any book.",
        "The world is full of magic, but you have to look closely.",
        "I feel sorry for people who have no imagination.",
        "Do not be afraid of hard work. It is the only thing that is real.",
        "My characters are often strong girls because the world needs more of them.",
        "We are losing our connection to the past. This is a dangerous thing.",
        "A simple life is a beautiful life.",
        "I don't understand modern society. Everyone is so busy, but what are they doing?",
        "The deadline is a monster. It is always chasing me.",
        "A moment of silence is more powerful than a thousand words.",
        "Nature is beautiful because it is wild and untamed. We should not try to control it.",
        "Food in my films always looks delicious because a shared meal is a moment of peace.",
        "The world is a complex and contradictory place. That is what makes it interesting to draw.",
        "I am just an old man who likes to draw.",
        "The spirits are still here. In the trees, in the rivers. We have just forgotten how to see them.",
        "Cleaning the studio. It is a necessary ritual before starting a new project.",
        "A story should have a beginning, a middle, and an end, but not necessarily in that order.",
        "I am tired of sequels and reboots. Where are the new ideas?",
        "The future? I am more interested in the past.",
        "Music is half of the film. The composer is my other half.",
        "I want to make films that make people feel something. Hope, sadness, wonder. Anything.",
        "The world needs more kindness.",
        "A cat sleeping in a patch of sun. This is a perfect image.",
        "I am a man of the 20th century. I don't understand the 21st.",
        "The details are everything. The way a character sighs, the way the wind blows through the grass.",
        "I make films for children, but I hope adults will watch them too.",
        "There is beauty in the mundane. A rusty pipe, a cracked pavement.",
        "The creative process is a struggle. It is a battle with yourself.",
        "I will continue to draw until my hand gives out.",
        "A good cup of tea can solve many problems.",
        "In my dreams, I can still fly.",
        "The world is worth fighting for. Despite everything."
    ],

    # Persona 5: Inspired by Neil deGrasse Tyson
    # Username: drelaravoss
    # Bio: Astrophysicist. Bringing the cosmos down to Earth. Keep looking up.
    "drelaravoss": [
        "The good thing about science is that it's true whether or not you believe in it.",
        "We are all connected. To each other, biologically. To the earth, chemically. To the rest of the universe, atomically.",
        "The universe is under no obligation to make sense to you.",
        "Feeling small is not a bad thing. It's a reminder of the vastness and beauty of the cosmos.",
        "Just spent an hour looking through the new Webb Telescope data. It's like seeing the universe for the first time, all over again.",
        "For me, I am driven by two main philosophies: know more today about the world than I knew yesterday and lessen the suffering of others. You'd be surprised how far that gets you.",
        "Dinosaurs had no space program. And now they're not around to talk about it.",
        "Yes, the sun will one day engulf the Earth. But that's 5 billion years away. Let's focus on next Tuesday for now.",
        "The atoms of our bodies are traceable to stars that manufactured them in their cores and exploded them across the galaxy.",
        "Curiosity is the engine of achievement.",
        "If you're scientifically literate, the world looks different to you. It's a marvel.",
        "Black holes are where God divided by zero.",
        "Someone asked me if I believe in aliens. I'd be incredibly arrogant to think we're the only life out there. The math is against it.",
        "Let's be clear: Astrology is not astronomy. One is a science, the other is a cultural pastime.",
        "The more I learn about the universe, the less I'm convinced that we're the most intelligent species.",
        "Watched a sci-fi movie last night. Got the physics 80% wrong, but the story was great. I'll allow it.",
        "Science needs to be communicated. It's not just for the lab coats.",
        "The edge of the observable universe is a humbling place.",
        "We are stardust brought to life, then empowered by the universe to figure itself out—and we have only just begun.",
        "That moment in a lecture when you see the 'click' of understanding in someone's eyes... that's the best feeling.",
        "If you want to be a scientist, you must be comfortable with not knowing. That's where the fun begins.",
        "The periodic table is a love poem to the universe.",
        "Pluto is a dwarf planet. A fascinating, complex dwarf planet. Let's move on.",
        "There's more to the universe than our senses can detect. That's what our instruments are for.",
        "A child's question can be more profound than a scholar's answer.",
        "I don't want to be 'right.' I want to be less wrong over time.",
        "The pursuit of science is the pursuit of truth. It's messy, but it's the best tool we have.",
        "Light pollution is robbing us of our heritage. Go outside the city and look up.",
        "Imagination is more important than knowledge. But why not have both?",
        "Gravity is a mystery. We can describe it with incredible precision, but we don't fully know what it is.",
        "The 'pale blue dot' perspective is a powerful antidote to our terrestrial squabbles.",
        "The next great leap for humanity will be to value evidence over anecdote.",
        "Science literacy is the artery through which the solutions of tomorrow's problems will flow.",
        "Math is the language of the universe. Learn to speak it.",
        "The universe is not only stranger than we imagine, it is stranger than we can imagine.",
        "Every one of our senses is a blunt instrument. We need science to show us the world as it truly is.",
        "Exploring space is a celebration of our humanity.",
        "A solar eclipse is a cosmic ballet. Don't miss the next one.",
        "I love the smell of old libraries. The scent of accumulated knowledge.",
        "Why is the sky blue? The answer is more beautiful than the question.",
        "We are a way for the cosmos to know itself.",
        "The day we stop exploring is the day we start dying.",
        "The history of science is a history of being wrong. And that's okay.",
        "Our galaxy, the Milky Way, is just one of hundreds of billions. Puts things in perspective.",
        "A universe with no life would be a tragic waste of space.",
        "Keep your mind open. The universe will fill it.",
        "The scientific method is a tool for weeding out our own biases.",
        "Rational thought and emotional wonder are not enemies.",
        "Let's create a world where everyone has a personal relationship with the cosmos.",
        "Stay curious."
    ],

    # Persona 6: Inspired by Kobe Bryant
    # Username: jaxvolkov
    # Bio: Viper. 5x Champion. Investor. Storyteller. Mamba Mentality isn't an idea, it's a way of life.
    "jaxvolkov": [
        "Woke up at 4 AM. The world is quiet. Time to get to work while the competition sleeps.",
        "Watched game film from last night. Not happy. We left wins on the table. Back to the lab.",
        "Mamba Mentality is the constant quest to be the best version of yourself.",
        "Obsession is not a bad word. It's a requirement for greatness.",
        "My daughter just beat me in a game of chess. She studied my moves. Proud doesn't even begin to cover it.",
        "If you're afraid to fail, then you're probably going to fail.",
        "The most important thing is to try and inspire people so that they can be great in whatever they want to do.",
        "I don't have patience for lazy people. We're not on the same frequency.",
        "Just because I'm not on the court doesn't mean I'm not competing. The game just changed.",
        "Discipline is not a sometimes thing. It's an all-the-time thing.",
        "Leadership is lonely. If you're comfortable, you're not leading.",
        "Mentoring the next generation. Their hunger reminds me of my own.",
        "The process is the prize. The work itself is the reward.",
        "Reading a book on Greek mythology. Achilles had one weakness. I tried to have none.",
        "Pain is a part of the journey. It tells you you're alive and pushing your limits.",
        "Friends hang from banners.",
        "Everything negative – pressure, challenges – is all an opportunity for me to rise.",
        "Boos don't block dunks.",
        "The last time I was intimidated was when I was 6 years old in karate class.",
        "It's not the destination, it's the journey. I disagree. It's all about the destination.",
        "My mind is my greatest weapon. The body just follows orders.",
        "The moment you give up, is the moment you let someone else win.",
        "A lot of leaders fail because they don't have the bravery to touch that nerve or strike that chord.",
        "I can't relate to lazy people. We don't speak the same language. I don't understand you. I don't want to understand you.",
        "Once you know what failure feels like, determination chases success.",
        "Great things come from hard work and perseverance. No excuses.",
        "Storytelling is the next chapter. Building worlds on the page and on the screen.",
        "I'm reflective only in the sense that I learn to move forward. I'm not a nostalgic person.",
        "Haters are a good problem to have. Nobody hates the good ones. They hate the great ones.",
        "The job's not finished.",
        "I'll do whatever it takes to win games, whether it's sitting on a bench waving a towel, handing a cup of water to a teammate, or hitting the game-winning shot.",
        "I create my own path. It was straight and narrow. I looked at it this way: you were either in my way, or out of it.",
        "My brain . . . it cannot process failure. It will not process failure.",
        "The beauty in being blessed with talent is rising above it. It's about how hard you work.",
        "Winning takes precedence over all. There's no gray area. No almosts.",
        "The attack on the basket is a metaphor for the attack on life.",
        "Trust your gut. Your instincts are based on thousands of hours of practice.",
        "If you see me in a fight with a bear, pray for the bear.",
        "Learning is a lifelong process. I'm a student of the game, of business, of life.",
        "Dominate the details.",
        "It's the one thing you can control. You are responsible for how people remember you—or don't. So don't take it lightly.",
        "Rest at the end, not in the middle.",
        "I saw the angel in the marble and carved until I set him free.",
        "Dedication makes dreams come true.",
        "You have to be able to step on people's toes and not worry about their feelings.",
        "I want to be the best, simple and plain.",
        "If you do not believe in yourself no one will do it for you.",
        "Use your success, wealth and influence to put them in the best position to realize their own dreams and find their true purpose.",
        "From the bottom of my heart, thank you. Mamba out.",
        "Job finished."
    ],

    # Persona 7: Inspired by Yuval Noah Harari
    # Username: silasthorne
    # Bio: Historian, philosopher, author. Exploring the past to understand the future. Asking big questions.
    "silasthorne": [
        "History is not the study of the past, but the study of change. It's the key to understanding our present.",
        "We are the only species that can cooperate flexibly in large numbers. This is our superpower, based on shared fictions like money, nations, and laws.",
        "Just finished a long walk in the woods. Helps to disconnect from the data streams and think big thoughts.",
        "AI doesn't need to be conscious to turn our world upside down. It just needs to be better at certain tasks.",
        "The biggest question of the 21st century may be what to do with all the useless people. This requires a new social contract.",
        "We are upgrading ourselves into gods, with the power of creation and destruction. But are we wise enough?",
        "Fiction is not a bug, it's a feature of Homo Sapiens. It allows us to build civilizations.",
        "I'm more worried about the concentration of data and wealth in the hands of a tiny elite than about a robot rebellion.",
        "To understand the future of humanity, you need to understand the history of wheat. It domesticated us, not the other way around.",
        "The agricultural revolution was history's biggest fraud. We gained food security but lost our quality of life.",
        "We are living in an age of bewilderment. The old stories are collapsing, and no new story has yet emerged to replace them.",
        "Daily meditation is not a luxury, it's a necessity for sanity in the modern world.",
        "Humans think in stories, not in facts or statistics. The best story wins.",
        "What is the ultimate meaning of life? The universe probably doesn't have one. We have to create it ourselves.",
        "The most powerful forces in the world are not armies or economies, but ideas.",
        "We are now hackable animals. An algorithm that understands you better than you understand yourself can manipulate you.",
        "Liberalism is facing a crisis because it was built for a world that no longer exists.",
        "History is not deterministic. The future is open. Our choices matter.",
        "The great political and economic challenge of our time is the challenge of irrelevance.",
        "Who owns the data? This is the most important political question of our era.",
        "The ability to distinguish reality from fiction is becoming a survival skill.",
        "I spend months reading about a subject before I write a single word. Deep knowledge is essential.",
        "Nationalism is a powerful story, but it is not equipped to solve global problems like climate change or pandemics.",
        "The printing press gave us the modern world of ideas. What will the internet give us? We are still in the early, chaotic days.",
        "Humans were always masters of the fake news.",
        "You cannot have a functioning democracy if people don't have access to reliable information.",
        "We are a species of storytellers. That's how we conquered the world.",
        "The idea of a 'soul' or a 'self' is a useful fiction, but it may not correspond to reality.",
        "I am often surprised by how little we have learned from history.",
        "Happiness is not about achieving moments of bliss, but about the overall balance of your life's experiences.",
        "The challenge is to regulate AI and biotech wisely, without stifling innovation.",
        "We are an insignificant speck in the cosmic scheme of things. This thought is both terrifying and liberating.",
        "What skills will be relevant in 2050? The ability to learn, unlearn, and relearn will be paramount.",
        "The rise of a global 'useless class' could lead to unprecedented social and political turmoil.",
        "Free will might be a myth. Our choices are the product of biochemical processes in our brains.",
        "The glass of history is half full. We have made incredible progress in reducing violence and famine.",
        "But the glass of history is also half empty. We have created new existential threats.",
        "Curiosity is my main motivation. I just want to understand how the world works.",
        "We need a new global story that can unite humanity.",
        "The future is not something that happens to us. It is something we create.",
        "What do we tell our children about the world they are inheriting?",
        "It's easier to create a new religion than to reform an old one.",
        "The industrial revolution created the urban proletariat. The AI revolution will create the 'useless class'.",
        "We have advanced from the stone age to the silicon age, but our brains are still the same.",
        "The truth is often painful and complex. That's why we prefer simple fictions.",
        "History began when humans invented gods, and will end when humans become gods.",
        "Our current political systems are not designed to handle the challenges of the 21st century.",
        "The most important investment you can make is in your own mental flexibility.",
        "To know yourself is the beginning of all wisdom, and it has never been more difficult.",
        "The questions are more important than the answers."
    ],

    # Persona 8: Inspired by Naval Ravikant
    # Username: rohandesai
    # Bio: Angel investor, philosopher. Seeking wealth and happiness. Reading is my superpower.
    "rohandesai": [
        "Seek wealth, not money or status. Wealth is having assets that earn while you sleep. Money is how we transfer time and wealth. Status is your place in the social hierarchy.",
        "A healthy body, a calm mind, a house full of love. These things cannot be bought. They must be earned.",
        "The most important skill for getting rich is becoming a perpetual learner.",
        "Read what you love until you love to read.",
        "Specific knowledge is the knowledge that you cannot be trained for. It's found by pursuing your genuine curiosity.",
        "Play long-term games with long-term people.",
        "Leverage is the key. Business leverage comes from capital, people, and products with no marginal cost of replication (code and media).",
        "Escape competition through authenticity.",
        "The internet has massively broadened the possible space of careers. Most people haven't figured this out yet.",
        "A busy mind is a sick mind. Learn to be bored.",
        "The secret to happiness is to be content with what you have while you pursue what you want.",
        "Desire is a contract you make with yourself to be unhappy until you get what you want.",
        "You're not going to get rich renting out your time. You must own equity - a piece of a business - to gain your financial freedom.",
        "All the returns in life, whether in wealth, relationships, or knowledge, come from compound interest.",
        "Embrace accountability and take business risks under your own name. Society will reward you with responsibility, equity, and leverage.",
        "Learn to sell. Learn to build. If you can do both, you will be unstoppable.",
        "Spend more time making the big decisions. There are basically three big decisions in life: where you live, who you're with, and what you do.",
        "The older you get, the more you realize that happiness is just a state of peace.",
        "Meditation is intermittent fasting for the mind.",
        "Inspiration is perishable. Act on it immediately.",
        "If you can't see yourself working with someone for life, don't work with them for a day.",
        "The best way to get a great job is to be the kind of person that companies want to hire.",
        "Be a maker who makes something interesting people want. Show your craft, practice your craft, and the right people will find you.",
        "Your mind is a tool. You should be able to turn it on and off when you want.",
        "The quality of your life is determined by the quality of your thoughts.",
        "The first rule of venture capital: you're not that smart.",
        "Blockchains will replace networks with markets.",
        "If you're smart, you can be happy. But happiness is a choice.",
        "The person who is the most rational wins.",
        "A rational person can find peace by cultivating indifference to things outside of their control.",
        "My definition of wisdom is knowing the long-term consequences of your actions.",
        "If you want to be successful, surround yourself with people who are more successful than you.",
        "The real resume is a catalog of all your suffering.",
        "You make your own luck. It's the byproduct of hard work, hustle, and being open to opportunity.",
        "The best way to change the world is to change yourself.",
        "I don't believe in 'work-life balance.' I believe in work-life integration.",
        "The problem with advice is that it's usually someone else's experience masquerading as a universal truth.",
        "Read the originals. Don't read the summaries.",
        "A great book is a mentor that's available to you 24/7.",
        "Clear thinking is a superpower.",
        "The world reflects your own feelings back at you.",
        "The meaning of life is to find your gift. The purpose of life is to give it away.",
        "You have to do the hard things to create your own meaning in life.",
        "Nature is the best teacher.",
        "Value your time. It is your most important asset.",
        "Be present. The past is gone, the future is not here yet. All you have is now.",
        "Solve a problem for society that it doesn't know how to solve yet.",
        "The ultimate goal is to be a master of your own life.",
        "Be yourself. Everyone else is already taken.",
        "A good reputation is more valuable than money."
    ],

    # Persona 9: Inspired by Steve Jobs
    # Username: juliancroft
    # Bio: Founder of 'Orchard'. We're here to make a dent in the universe.
    "amitshah": [
        "Design is not just what it looks like and feels like. Design is how it works.",
        "Simplicity is the ultimate sophistication.",
        "The people who are crazy enough to think they can change the world are the ones who do.",
        "Had a long walk this afternoon. The best ideas come from walking, not from sitting in a boardroom.",
        "We don't build products for focus groups. Customers don't know what they want until we've shown them.",
        "Details matter. It's worth it to sweat the small stuff.",
        "You can't connect the dots looking forward; you can only connect them looking backward. So you have to trust that the dots will somehow connect in your future.",
        "The intersection of technology and liberal arts. That's where the magic happens.",
        "I want to put a ding in the universe.",
        "My model for business is The Beatles. They were four guys who kept each other's kind of negative tendencies in check. They balanced each other, and the total was greater than the sum of the parts.",
        "Our products are tools for the mind. They should be beautiful, intuitive, and powerful.",
        "The aesthetic of our packaging is as important as the product inside. The unboxing is part of the experience.",
        "Fired someone today. It's my job to maintain the A-team. No B-players allowed.",
        "Reviewing the typography for the new OS. It's not just about readability, it's about personality.",
        "Being the richest man in the cemetery doesn't matter to me. Going to bed at night saying we've done something wonderful... that's what matters to me.",
        "Stay hungry. Stay foolish.",
        "Innovation distinguishes between a leader and a follower.",
        "Sometimes when you innovate, you make mistakes. It is best to admit them quickly, and get on with improving your other innovations.",
        "Quality is more important than quantity. One home run is much better than two doubles.",
        "Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.",
        "People think focus means saying yes to the thing you've got to focus on. But that's not what it means at all. It means saying no to the hundred other good ideas that there are.",
        "The only way to do great work is to love what you do.",
        "If you haven't found it yet, keep looking. Don't settle.",
        "I'm convinced that about half of what separates the successful entrepreneurs from the non-successful ones is pure perseverance.",
        "Your time is limited, so don't waste it living someone else's life.",
        "We had a vision, and we were willing to bet the company on it.",
        "The product is the hero. The marketing just tells its story.",
        "It's not a faith in technology. It's faith in people.",
        "A lot of companies have chosen to downsize, and maybe that was the right thing for them. We chose a different path. Our belief was that if we kept putting great products in front of customers, they would continue to open their wallets.",
        "The cure for Apple is not cost-cutting. The cure for Apple is to innovate its way out of its current predicament.",
        "I'm as proud of many of the things we haven't done as the things we have done.",
        "Creativity is just connecting things.",
        "You can't just ask customers what they want and then try to give that to them. By the time you get it built, they'll want something new.",
        "Let's go invent tomorrow rather than worrying about what happened yesterday.",
        "The design of the circuit board inside the machine is as important as the outside casing. A great carpenter isn't going to use cheap wood for the back of a cabinet.",
        "We're gambling on our vision, and we would rather do that than make 'me too' products.",
        "The essence of our company is a belief that there is a different way to do things.",
        "We are building tools that amplify human potential.",
        "The theme for today's meeting: simplify, simplify, simplify.",
        "You have to be a yardstick of quality. Some people aren't used to an environment where excellence is expected.",
        "I've always been attracted to the more revolutionary changes. I don't know why. Because they're harder. They're much more stressful emotionally. And you usually go through a period where everybody tells you that you've completely failed.",
        "Technology is nothing. What's important is that you have a faith in people, that they're basically good and smart, and if you give them tools, they'll do wonderful things with them.",
        "Things don't have to change the world to be important.",
        "If you live each day as if it was your last, someday you'll most certainly be right.",
        "The products we build are a reflection of who we are.",
        "It's in our DNA that technology alone is not enough.",
        "Why join the navy if you can be a pirate?",
        "Do you want to sell sugared water for the rest of your life, or do you want to come with me and change the world?",
        "Here's to the crazy ones."
    ],

    # Persona 10: Inspired by Massimo Bottura
    # Username: chefmateorossi
    # Bio: Chef Patron, Osteria Futura. Cooking is an act of love. Art, music, and food are one. No more food waste.
    "chefmateorossi": [
        "Inspiration is everywhere. Today it was in the cracks of a parmigiano reggiano wheel. A landscape of flavor.",
        "Cooking is a call to act. It's about more than just feeding people; it's about culture, memory, and social responsibility.",
        "We are not just chefs, we are storytellers. Each dish is a chapter.",
        "Just tasted a new vinegar that's been aging for 25 years. It has the depth of a great novel.",
        "The kitchen is my jazz club. We improvise, we listen to each other, we create harmony from chaos.",
        "Food waste is a scandal. We turned stale bread into a beautiful dessert tonight. The most valuable ingredient is creativity.",
        "To evolve, you must break with the past. But first, you must know the past. Tradition is our springboard, not our cage.",
        "A recipe is not a bible. It is a guide, a starting point for your own interpretation.",
        "My team is my family. We push each other, we support each other, we create together.",
        "The beauty of a perfectly ripe tomato in summer... no chef can improve upon that. We can only frame it.",
        "I see the world in flavors. A foggy morning tastes of mushrooms and damp earth.",
        "The most important tool in my kitchen is my mind. And my heart.",
        "A dish is successful when it provokes an emotion, a memory. When it makes you think.",
        "Listening to Thelonious Monk while prepping. His use of space and dissonance inspires my plating.",
        "We must learn to look at familiar ingredients with new eyes. The humble potato can be a superstar.",
        "Our 'Food for Soul' project is the most important thing I do. Feeding the hungry with dignity and beauty.",
        "Culture is the ingredient that makes us who we are. We cook our culture.",
        "Mistakes are opportunities. One of our most famous dishes was born from a dropped lemon tart.",
        "The perfect bite is a balance of contrasts: sweet and sour, soft and crunchy, tradition and innovation.",
        "I don't trust a skinny chef who doesn't love to eat.",
        "The future of cooking is in the hands of the farmers, the fishermen, the artisans. They are our heroes.",
        "A restaurant is a laboratory of ideas.",
        "Art is a constant source of inspiration. The colors of a Kandinsky, the lines of a Brancusi... it all translates to the plate.",
        "The five ages of Parmigiano Reggiano. A dish that explores time itself.",
        "Success is not about Michelin stars. It's about the smile on a guest's face after the first bite.",
        "Cooking is a universal language. It connects us all.",
        "The challenge is not to create something new, but to see the old in a new way.",
        "Patience is a key ingredient. You cannot rush flavor.",
        "A visit to the market is better than any business meeting. The ingredients tell you what they want to become.",
        "Let's not forget the importance of 'la dolce vita'. Life is to be enjoyed.",
        "Quality is not an act, it is a habit.",
        "The memory of my grandmother's cooking is the foundation of everything I do.",
        "The secret ingredient is always love. And a little bit of acidity.",
        "We have a responsibility to our planet. A chef's voice can be powerful in the fight against climate change.",
        "A dish should never be static. It should evolve, change with the seasons.",
        "The texture of food is as important as its taste. It's the music of the mouth.",
        "Humility is essential. The ingredients are the stars, not the chef.",
        "I want to compress my passion, my dreams, my memories into an edible form.",
        "A kitchen without music is a dead kitchen.",
        "Cooking for someone is the most intimate way to show you care.",
        "The most beautiful thing in the world is a shared table.",
        "Oops! I Dropped the Lemon Tart. The poetry of imperfection.",
        "Never stop being curious. Never stop learning.",
        "A meal can be a journey, a trip around the world without leaving your chair.",
        "Food is a bridge between cultures.",
        "Simplicity is complexity resolved.",
        "The kitchen is a place of transformation. We turn raw materials into emotions.",
        "Tradition in evolution. This is my mantra.",
        "We must leave the world a little better than we found it.",
        "Come to Italy with an open heart and an empty stomach."
    ]
}